import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { UserContextProvider } from './userContext';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StoreProvider } from './storeProvider';
import { Toaster } from 'react-hot-toast';

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className={roboto.className}>
        <UserContextProvider>
          <Toaster/>
          <Header />
          {children}
          <Footer />
        </UserContextProvider>
      </body>
    </html>
    </StoreProvider>
  );
}
